
CREATE TABLE ACTOR
	(COD_ACT CHAR(5 BYTE),
	NOMBRE VARCHAR2(70 CHAR) NOT NULL,
	FECHA_NAC DATE NOT NULL,
	NOM_PAIS VARCHAR2(20 CHAR) NOT NULL
	CONSTRAINT PK_ACTOR PRIMARY KEY (COD_ACT));

CREATE TABLE ACTUA
	(COD_ACT CHAR(5 BYTE)
	COD_PELI CHAR(5 BYTE),
	PAPEL VARCHAR2(10 CHAR) NOT NULL,
	CONSTRAINT PK_ACTUA PRIMARY KEY (COD_ACT, COD_PELI),
	CONSTRAINT FK_ACTUA FOREIGN KEY (COD_PELI) REFERENCES (COD_PELI),
	CONSTRAINT FK_ACTUA FOREIGN KEY (COD_ACT) REFERENCES (COD_ACT),
	CHECK PAPEL IN ('Principal', 'Secundario'));

INSERT INTO LIBRO (COD_LIB, TITULO, ANYO, AUTOR)
	SELECT * FROM CS_LIBRO;

INSERT INTO PELICULA (COD_PELI, TITULO, ANYO, DURACION, COD_LIB, DIRECTOR)
	SELECT * FROM CS_PELICULA WHERE ANYO > 2000;

INSERT INTO ACTOR (COD_ACT, NOMBRE, FECHA_NAC, NOM_PAIS)
    SELECT * FROM CS_ACTOR A WHERE A.COD_ACT IN (
        SELECT AC.COD_ACT FROM CS_ACTUA AC WHERE AC.COD_PELI IN (
            SELECT P.COD_PELI FROM CS_PELICULA P WHERE ANYO > 2000));
UPDATE ACTOR A SET A.NOM_PAIS = 
    (SELECT PA.NOMBRE FROM CS_PAIS PA WHERE PA.COD_PAIS = A.NOM_PAIS);

/*	Alternative

INSERT INTO ACTOR (COD_ACT, NOMBRE, FECHA_NAC, NOM_PAIS)
    SELECT A.COD_ACT, A.NOMBRE, A, FECHA_NAC, PA.NOMBRE
    FROM CS_ACTOR A, CS_PAIS PA
    WHERE PA.COD_PAIS = A.NOM_PAIS AND A.COD_ACT IN (
        SELECT AC.COD_ACT FROM CS_ACTUA AC WHERE AC.COD_PELI IN (
            SELECT P.COD_PELI FROM CS_PELICULA P WHERE ANYO > 2000));
*/

INSERT INTO ACTUA (COD_ACT, COD_PELI, PAPEL)
    SELECT AC.COD_ACT, AC.COD_PELI, AC.PAPEL FROM CS_ACTUA AC WHERE PAPEL IS NOT NULL AND AC.COD_PELI IN (
            SELECT P.COD_PELI FROM CS_PELICULA P WHERE P.ANYO > 2000);

COMMIT;